sensor_msgs/PointCloud2 input     # the input point cloud
string waypoint     # the waypoint of the observation
---
bool result         # whether the service succeded or failed
string[] objects   # IDs of all SOMA objects present in this view
